version: "3.5"

services:
  api01: &api
    #image: kfg/rinha-backend:latest
    build: .
    hostname: api01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=db
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200MB"
    restart: always

  api02:
    <<: *api 
    hostname: api02
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=db
      - PORT=3000
    ports:
      - "3002:3000"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1